language: objective-c
osx_image: xcode7
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project Revolver/Revolver.xcodeproj -scheme Revolver
#- xctool test -project Revolver/Revolver.xcodeproj -scheme RevolverTests
